### ISSUE TITLE
Change Request | Support Matrix 

### ISSUE THREAD

**Issue by Nao-Maeshiro** [dell/azurestack-docs#46] opened 2023-11-13 03:35 UTC
Please refer to the attached for details.
[Change Request.docx](https://github.com/dell/azurestack-docs/files/13330509/Change.Request.docx)

**Comment by cblackuk** [comment] 2023-11-15 16:56
Duplicate of https://github.com/dell/azurestack-docs/issues/45

**Comment by cblackuk** [comment] 2023-11-15 16:57
Will take into consideration when looking at https://github.com/dell/azurestack-docs/issues/45

**Closed by cblackuk** 2023-11-15 16:57 UTC
